// ============================================================================
//  BROOKDALE LEAGUE — 2026 PRESEASON POWER RANKINGS — WRITE-UPS
//
//  This is YOUR file. One entry per team, keyed by the `slug` from data.js.
//    tagline: one short line shown next to the file in the list (optional, can be "").
//    text:    the write-up. Plain text between the backticks. A blank line starts a
//             new paragraph; single line breaks inside a paragraph are joined.
//             Avoid the backtick character ` inside the text (use ' instead).
//  If `text` is empty the site shows "[REDACTED] — write-up pending decryption".
//  The site renders every write-up in ALL CAPS with terminal coloring (player names green,
//  numbers/records/odds amber, team names blue) — you can type in any case.
// ============================================================================

window.WRITEUPS = {

  "hoes-mad": {
    tagline: "",
    text: `
ALEX FROZE ME ON THIS ONE. GOT CEEDEE WHEN I THOUGHT I HAD HIM, THEN GRABBED AJ RIGHT AS I WAS SECOND-GUESSING MYSELF.
TO BE FAIR, HE PROBABLY COULDN'T BELIEVE HIS LUCK EITHER. AFTER A FLOP ERA THAT RESEMBLED THE 2014 LAKERS, ANK IS BACK
IN FORCE AS A TRUE BROOKDALE LEAGUE JUGGERNAUT. THE MAN ONLY KNOWS BALL DURING A TRUMP ADMINISTRATION. ITS EITHER THAT
OR THE GRIEVING PERIOD AS A RESULT OF GETTING DUMPED. 2023 AND 2024 WERE NOT A FLOP ERA. THEY WERE A GRIEVING PERIOD.
HE HAS SINCE MADE ZERO PROGRESS ON THE GIRLFRIEND FRONT AND INSTEAD POURED EVERY OUNCE OF THAT ENERGY INTO FANTASY
FOOTBALL. THE RESULTS ARE ON THE SCREEN. MY MODELS SAY ITS HIGH TIME FOR THE FIRST BROOKDALE LEAGUE 3 PEAT.
`,
  },

  "hammertime": {
    tagline: "",
    text: `
I DON’T UNDERSTAND THIS CALEB RENAISSANCE ERA. I KNOW HE WASN’T MOCKING. I KNOW HE WASN’T WATCHING FILM. I KNOW HE
WASN’T ON FOOTBALL ABSURDITY EXPECTING VALUE RANKINGS. I KNOW HE DOESN’T USE AI. I KNOW HE DOESN’T PARTICULARLY CARE
ABOUT THE OUTCOME OF THIS SEASON OR EVEN HIS LEGACY IN THE BROOKDALE LEAGUE. I KNOW THAT HE KEEPS THIS THING TOGETHER
WITH MINIMAL EFFORT YEAR AFTER YEAR DUE TO SOME CONVOLUTED OBLIGATION TO THE SOCIAL CONTRACT HE SIGNED WHEN WE WERE
SMOKING GROUND UP SMARTIES IN THE LUNCH ROOM. BUT I DO KNOW THAT CALEB KNOWS BALL. AND I’M NOT SURE IF IT WAS THAT OR
SHEER LUCK BUT CALEB ENDED UP WITH A BANGER SQUAD. I SEE GREAT THINGS FOR THIS BEAUTIFUL TEAM. PLAYOFFS AND EVEN BETTER
IF HE DOESN’T FALL ASLEEP AT THE WHEEL.
`,
  },

  "mr-glass-reborn": {
    tagline: "",
    text: `
AFTER THE FIRST MONTH OF THE GABE ERA I SERIOUSLY CONSIDERING STAGING AN ATTEMPT TO HAVE HIM PERMANENTLY BLACKLISTED
FROM THE BROOKDALE LEAGUE AND ALL FORMS OF SOCIAL INTERACTION WITH ANY MEMBER. BUT BOY OH BOY HE TURNED THINGS AROUND:
A DEEP PLAYOFF RUN AND BACK TO BACK SUPERTEAMS. YEAH HIS TEAM SUCKED LAST YEAR BUT I THINK IT WAS A CLASSIC MOMENT OF
HUBRIS. HE TOOK THIS SUCCESS FOR GRANTED AND LEARNED AS WE ALL HAVE THAT NOTHING IS EVER GIVEN TO YOU IN THIS LEAGUE,
YOU HAVE TO TAKE IT. THIS ALSO INCIDENTALLY IS WHY I THINK GABE IS CHEATING SOMEHOW. THIS IS THE FANTASY EQUIVALENT OF
TURNING OFF WALL HACKS BECAUSE YOU HAVE CONVINCED YOURSELF THAT YOU DON’T NEED THEM ANYMORE. BUT THE WALLS ARE BACK ON
AND GABE XRAYED TO A BANGER DRAFT (MAYBE TURNED THEM OFF FOR LUTHER BURDEN). ANOTHER SUPERTEAM BREWING.
`,
  },

  "saxwillruintheleague": {
    tagline: "",
    text: `
I’M NOT GOING TO SIT HERE AND EXPLAIN MYSELF. I’M NOT GOING TO TRY TO BE HUMBLE OR TRY TO BE BRASH. MAYBE I DID BLACK
OUT AROUND PICK 20. MAYBE I DID MISCLICK ON KYREN AND END UP WITH LOVE BUT WAS TOO SCARED TO ADMIT IT IN THE MOMENT OR
BEG CALEB FOR FORGIVENESS. MAYBE I DID OVERCOMPENSATE AND GO FULL FUCKING HOMER AND DRAFTED THE STACK OF AN OFFENSE
THAT MOST NOTABLY LED THE LEAGUE IN RUSHING DURING THEIR IMPROBABLE 2024-25 RUN. OR MAYBE EVERYTHING WENT EXACTLY TO
PLAN. MAYBE MY UNCERTAINTY WAS SMOKE THE WHOLE TIME AND AM THRILLED WITH HOW MY ROSTER LANDED. MAYBE I SAY RIGHT NOW
THAT LOVE WILL BE A TOP 5 RB. MAYBE I BOLDLY SAY THAT ONCE AGAIN, THE TEAM WITH THE BEST RB1/2 PUNCH WILL WIN THE
LEAGUE.
`,
  },

  "killer-whales": {
    tagline: "",
    text: `
I HATE GRADING CHRIS’S TEAM BECAUSE ANYTHING LESS THAN 1-2 HE WILL BE EXPLAINING TO YOU WHY YOU ARE WRONG. THIS GOES
FROM SOMEWHAT RESPECTFUL AT A 3-5 RANKING TO ABSOLUTE VERBAL ABUSE ANYTHING OUTSIDE PLAYOFFS. CHRIS’S TEAM IS A BROKEN
FAMILY. JUST LIKE A DEADBEAT FATHER, YOU CAN NEVER COUNT ON JAMO TO PROVIDE FOR YOU IN MOMENTS OF GREAT NEED. JUST LIKE
THE FAILING ELDEST SON, YOU HAVE PUT ALL YOUR HOPES AND DREAMS INTO ASHTON JEANTY JUST TO BE LET DOWN, PARTIALLY BY
CIRCUMSTANCES OUT OF HIS CONTROL. JUST LIKE THE FAT DAUGHTER, KYREN WILLIAMS IS A PLODDER WITH NO SENSE OF SELF WORTH.
JUST LIKE THE FORGOTTEN HIGH PERFORMING MIDDLE CHILD, I DON’T CARE IF YOU HAVE BRANDON AUBREY. LUCKILY FOR HIM I HAVE
NOTHING BAD TO SAY ABOUT JAMARR CHASE AND THUS THIS TEAM EKES OUT A PLAYOFF SPOT.
`,
  },

  "schkattebooboo": {
    tagline: "",
    text: `
THE MOST BEN TEAM EVER. ONE TO TWO SUPERSTARS (PUKA + RASHEE), AND A BUNCH OF RB2S AND RB3S THAT BEN WILL ATTEMPT TO
PAWN OFF AS RB1S AND RB2S. EVERY SINGLE PLAYER EXCEPT 3 I COULD SEE BEING DROPPABLE. BUT YET, THE UPSIDE IS THROUGH
THE ROOF. EASILY THE HIGHEST VARIANCE TEAM IN THE LEAGUE. THE WRITING IS ON THE WALL: IN BEN FASHION, A QUICK START,
SQUANDERS HIS CHANCE TO SELL HIGH BOTH DUE TO HIS OWN GENERAL INEPTITUDE AND HOSTILITY BUT ALSO THE GENERAL
UNWILLINGNESS OF THE LEAGUE TO MAKE ANYTHING HAPPEN WITH HIM (DUE TO THE SENTIMENT THAT ANY TRADE BEN OFFERS PROBABLY
VIOLATES THE GENEVA CONVENTION), LIMPS TO THE PLAYOFF/CONSOLATION FRINGE, AND DOES ABSOLUTELY NOTHING IN POSTSEASON.
HOW MANY TIMES DO I HAVE TO WATCH THE SAME MOVIE.
`,
  },

  "eyes-wide-shut": {
    tagline: "",
    text: `
ANOTHER BORING ASS TEAM FROM SAM. I THOUGHT IT COULDN’T GET WORSE THAN LAST YEAR BUT HE PROVED ME WRONG ONCE AGAIN.
WITH THE POSSIBLE EXCEPTION OF DERRICK HENRY (GENERAL BIAS DUE TO HIM DELIVERING ME TWO RINGS IN 4 YEARS) THERE IS NOT
A SINGLE PERSON ON THIS TEAM THAT MAKES ME WANT TO GET OUT OF BED ON A SUNDAY MORNING AFTER A LONG NIGHT OUT TO WATCH
SOME FOOTBALL. PROBABLY THE WORST SAM TEAM I HAVE EVER EVALUATED. I DON’T KNOW WHICH ARM CHAIR ANALYST ON REDDIT SOLD
HIM ON LADD (MOST LIKELY SOME CHERRY PICKED STAT ON WHY LADD MCCONKEY WILL BE THE WR1 OVERALL SOLD BY SOMEONE TRYING
TO TRICK THEIR LEAGUE MATES INTO A REACH (MAYBE ME)) BUT I PREDICT NOT A SINGLE TOP 20 WR ON THIS TEAM. ANY PERSON WHO
DRAFTS TWO WHITE WRS IN ONE DRAFT DESERVES JAIL TIME. SEE YOU IN CANCUN BUDDY
`,
  },

  "dhhate": {
    tagline: "",
    text: `
NEVER IN HUMAN HISTORY HAS A BIGGER HUMBLING OCCURRED THAN OLIVER ENTERING THE LEAGUE CLAIMING IT WAS ALL LUCK AND
PROCEEDED TO SKILL HIMSELF TO A 10TH PLACE FINISH. WHAT ONCE WAS A WRONG BUT LEGITIMATE BELIEF THAT DERRICK HENRY WAS
WASHED HAS DUG HIM INTO A HOLE THAT HE HAS DECIDED THE ONLY WAY TO CLIMB OUT OF IS TO DIG THROUGH THE CORE AND OUT AT
THE OTHER SIDE IN CHINA. I’M NOT SURE IF IT’S GENERAL STUBBORNNESS/UNWILLINGNESS TO ADMIT FAILURE OR LACK OF BALL
KNOWLEDGE ON THE WELL DOCUMENTED DERRICK HENRY PLAYOFF TURN UP BUT ITS LIKE WATCHING A CGI SOPHOMORE TRYING TO DEFEND
THEIR ABOLISH ALL DRUGS BILLS IN FRONT OF A CONGRESS FULL OF IVY LEAGUE COMMITS. ON A PRAGMATIC NOTE, OLIVER AND ETHAN
DRAFTED THE SAME TEAM. I HAPPENED TO THINK OLIVER HAS A SLIGHT EDGE ON THE HEAVY HITTERS NOW THAT I CAN ADMIT THAT MY
DEVALUE KW9 CAMPAIGN FAILED MISERABLY SO ILL TAKE HIM HERE BUT THIS IS A PURE COIN FLIP BETWEEN THE TWO TEAMS.
`,
  },

  "mac-and-movies": {
    tagline: "",
    text: `
AFTER A HOT STREAK THAT LASTED MOST OF THE 2020S (A RING, A FINALS APPEARANCE, FOUR TOP 3 FINISHES IN FIVE YEARS),
ETHAN CRASHED DOWN TO EARTH LAST YEAR AND FOR THE FIRST TIME IN LEAGUE HISTORY HE WAS THE LOWEST PLACING JEW. HIS
SCHIZOPHRENIC DELUSIONS LAST YEAR SHATTERED THE AURA OF SOMEONE WHO KNEW SOMETHING THE REST OF US DIDN'T.
UNFORTUNATELY IT APPEARS THIS WAS NOT A ONE TIME OCCURRENCE AND ETHAN HAS COMPLETELY AND UTTERLY LOST HIS TOUCH. IT
APPEARS HE HAS TRANSITIONED FROM DOCTOR STRANGE TO DOC BROWN FROM BACK TO THE FUTURE. MAYBE I DON’T KNOW BALL BUT
THIS IS THE WORST BENCH IN THE LEAGUE. I HAVE INSIDER INFORMATION THAT AMON RA AND THE LIONS WILL HAVE A DISASTER
YEAR. ANYONE WHO DRAFTS BACK TO BACK TIGHT ENDS NEEDS TO BE INSTITUTIONALIZED (AS I LEARNED IN 2023). GO BACK TO THE
FLOW CHARTS ETHAN.
`,
  },

  "hogwash": {
    tagline: "",
    text: `
I’M TRYING NOT TO PUNCH DOWN HERE BUT HE MAKES ME WANT TO PUNCH. IT’S GOOD BELSKY HAS NO FREE TIME DUE TO WORK BECAUSE
HE WOULD CLEARLY HAVE A DEBILITATING GAMBLING ADDICTION OTHERWISE. THIS IS A MAN HELLBENT ON SELF DESTRUCTION AT EVERY
CORNER. SOMEHOW A MAN WHO HAS GOTTEN FUCKED EVERY YEAR BY HIGH VARIANCE DRAFTING HAS DECIDED THAT THE LUCK HAS TO SWING
HIS WAY THIS TIME AND ONCE AGAIN DRAFTED ALL UPSIDE. I’M NOT SURE IF HE HAS CRIED HIMSELF TO BED ABOUT THE JACOBS PICK
BUT I KNOW HE WILL BEFORE ITS ALL SAID AND DONE. I KNOW HE HASN’T CRIED ABOUT HIMSELF TO BED ABOUT CMC BUT HISTORY SAYS
THAT HE WILL BEFORE ITS ALL SAID AND DONE. THIS IS A MAN WHO WALKS AND TALKS LIKE HE HAS DIPLOMATIC IMMUNITY BUT IS THE
LEAGUES PUNCHING BAG. THIS IS A MATCHUP THAT EVERYONE IS ALREADY LICKING THEIR LIPS FOR AND THE SEASON HASN’T ALREADY
STARTED. HE WILL BE LOOKING AT THE 2027 NFL ROOKIE CLASS BY OCTOBER.
`,
  },

};
